
select dbms_metadata.get_ddl('TABLE', 'CONSTRUCTOR_STANDINGS')
from dual;
------------------------------------------------------------------------------
--TABLE CREATION 
------------------------------------------------------------------------------
  CREATE TABLE   RESULTS  
   (	 RESULTID  NUMBER, 
	 RACEID  NUMBER, 
	 DRIVERID  NUMBER, 
	 CONSTRUCTORID  NUMBER, 
	 NUMBER_RW  NUMBER, 
	 GRID  NUMBER, 
	 POSITION  NUMBER, 
	 POSITIONTEXT  VARCHAR2(64)  , 
	 POSITIONORDER  NUMBER, 
	 POINTS  NUMBER, 
	 LAPS  NUMBER, 
	 TIME  VARCHAR2(64)  , 
	 MILLISECONDS  NUMBER, 
	 FASTESTLAP  NUMBER, 
	 RANK  NUMBER, 
	 FASTESTLAPTIME  VARCHAR2(64)  , 
	 FASTESTLAPSPEED  NUMBER, 
	 STATUSID  NUMBER
   )   
  CREATE TABLE   QUALIFYING  
   (	 QUALIFYID  NUMBER, 
	 RACEID  NUMBER, 
	 DRIVERID  NUMBER, 
	 CONSTRUCTORID  NUMBER, 
	 NUMBER_RW  NUMBER, 
	 POSITION  NUMBER, 
	 Q1  VARCHAR2(64)  , 
	 Q2  VARCHAR2(64)  , 
	 Q3  VARCHAR2(64)  
   )   
  CREATE TABLE   CONSTRUCTOR_RESULTS  
   (         CONSTRUCTORRESULTSID  NUMBER, 
         RACEID  NUMBER, 
         CONSTRUCTORID  NUMBER, 
         POINTS  NUMBER, 
         STATUS  VARCHAR2(64)  
   )   
  CREATE TABLE   DRIVER_STANDINGS  
   (	 DRIVERSTANDINGSID  NUMBER, 
	 RACEID  NUMBER, 
	 DRIVERID  NUMBER, 
	 POINTS  NUMBER, 
	 POSITION  NUMBER, 
	 POSITIONTEXT  NUMBER, 
	 WINS  NUMBER
   )   
  CREATE TABLE   STATUS  
   (	 STATUSID  NUMBER, 
	 STATUS  VARCHAR2(64)  
   )   
  CREATE TABLE   CONSTRUCTOR_STANDINGS  
   (	 CONSTRUCTORSTANDINGSID  NUMBER, 
	 RACEID  NUMBER, 
	 CONSTRUCTORID  NUMBER, 
	 POINTS  NUMBER, 
	 POSITION  NUMBER, 
	 POSITIONTEXT  VARCHAR2(64)  , 
	 WINS  NUMBER
   )   
  CREATE TABLE   RACES  
   (	 RACEID  NUMBER, 
	 YEAR  NUMBER, 
	 ROUND  NUMBER, 
	 CIRCUITID  NUMBER, 
	 NAME  VARCHAR2(64)  , 
	 DATE_RW  DATE, 
	 TIME  VARCHAR2(64)  , 
	 URL  VARCHAR2(64)  , 
	 FP1_DATE  VARCHAR2(64)  , 
	 FP1_TIME  VARCHAR2(64)  , 
	 FP2_DATE  VARCHAR2(64)  , 
	 FP2_TIME  VARCHAR2(64)  , 
	 FP3_DATE  VARCHAR2(64)  , 
	 FP3_TIME  VARCHAR2(64)  , 
	 QUALI_DATE  VARCHAR2(64)  , 
	 QUALI_TIME  VARCHAR2(64)  , 
	 SPRINT_DATE  VARCHAR2(64)  , 
	 SPRINT_TIME  VARCHAR2(64)  
   )   
  CREATE TABLE   PIT_STOPS  
   (	 RACEID  NUMBER, 
	 DRIVERID  NUMBER, 
	 STOP  NUMBER, 
	 LAP  NUMBER, 
	 TIME  VARCHAR2(64)  , 
	 DURATION  VARCHAR2(64)  , 
	 MILLISECONDS  NUMBER
   )   
  CREATE TABLE   SPRINT_RESULTS  
   (	 RESULTID  NUMBER, 
	 RACEID  NUMBER, 
	 DRIVERID  NUMBER, 
	 CONSTRUCTORID  NUMBER, 
	 NUMBER_RW  NUMBER, 
	 GRID  NUMBER, 
	 POSITION  VARCHAR2(64)  , 
	 POSITIONTEXT  VARCHAR2(64)  , 
	 POSITIONORDER  NUMBER, 
	 POINTS  NUMBER, 
	 LAPS  NUMBER, 
	 TIME  VARCHAR2(64)  , 
	 MILLISECONDS  VARCHAR2(64)  , 
	 FASTESTLAP  VARCHAR2(64)  , 
	 FASTESTLAPTIME  VARCHAR2(64)  , 
	 STATUSID  NUMBER
   )   
  CREATE TABLE   LAP_TIMES  
   (	 RACEID  NUMBER, 
	 DRIVERID  NUMBER, 
	 LAP  NUMBER, 
	 POSITION  NUMBER, 
	 TIME  VARCHAR2(64)  , 
	 MILLISECONDS  NUMBER
   )   
  CREATE TABLE   CIRCUITS  
   (	 CIRCUITID  NUMBER, 
	 CIRCUITREF  VARCHAR2(64)  , 
	 NAME  VARCHAR2(64)  , 
	 LOCATION  VARCHAR2(64)  , 
	 COUNTRY  VARCHAR2(64)  , 
	 LAT  NUMBER, 
	 LNG  NUMBER, 
	 ALT  VARCHAR2(64)  , 
	 URL  VARCHAR2(256)  
   )   
  CREATE TABLE   CONSTRUCTORS  
   (	 CONSTRUCTORID  NUMBER, 
	 CONSTRUCTORREF  VARCHAR2(64)  , 
	 NAME  VARCHAR2(64)  , 
	 NATIONALITY  VARCHAR2(64)  , 
	 URL  VARCHAR2(256)  
   )   
  CREATE TABLE   DRIVERS  
   (	 DRIVERID  NUMBER, 
	 DRIVERREF  VARCHAR2(64)  , 
	 NUMBER_RW  VARCHAR2(64)  , 
	 CODE  VARCHAR2(64)  , 
	 FORENAME  VARCHAR2(64)  , 
	 SURNAME  VARCHAR2(64)  , 
	 DOB  DATE, 
	 NATIONALITY  VARCHAR2(64)  , 
	 URL  VARCHAR2(256)  
   )  
------------------------------------------------------------------------------
--Primary key addition
------------------------------------------------------------------------------
ALTER TABLE RESULTS ADD CONSTRAINT FK_resultId PRIMARY KEY (resultId);

ALTER TABLE QUALIFYING ADD CONSTRAINT FK_qualifyId PRIMARY KEY (qualifyId);

ALTER TABLE CONSTRUCTOR_RESULTS ADD CONSTRAINT FK_constructorResultsId PRIMARY KEY (constructorResultsId);

ALTER TABLE DRIVER_STANDINGS ADD CONSTRAINT fk_driverStandingsId PRIMARY KEY (driverStandingsId);

ALTER TABLE STATUS ADD CONSTRAINT FK_statusId PRIMARY KEY (statusId);

ALTER TABLE CONSTRUCTOR_STANDINGS ADD CONSTRAINT FK_constructorStandingsId PRIMARY KEY (constructorStandingsId);

ALTER TABLE RACES ADD CONSTRAINT FK_raceId PRIMARY KEY (raceId);

ALTER TABLE PIT_STOPS
 ADD CONSTRAINT FK_raceId1 FOREIGN KEY (raceId)
 REFERENCES RACES (raceId);

 ALTER TABLE CONSTRUCTORS
 ADD CONSTRAINT FK_constructorId PRIMARY KEY(constructorId);

 ALTER TABLE CIRCUITS
 ADD CONSTRAINT FK_circuitId PRIMARY KEY(circuitId);

 ALTER TABLE DRIVERS
 ADD CONSTRAINT FK_driverId PRIMARY KEY(driverId);

------------------------------------------------------------------------------
--FOREIGN KEY ADDITION
------------------------------------------------------------------------------
ALTER TABLE RESULTS
 ADD CONSTRAINT FK_raceId01 FOREIGN KEY (raceId) 
 REFERENCES RACES (raceId);

  ALTER TABLE RESULTS
 ADD CONSTRAINT FK_driverId01 FOREIGN KEY (driverId) 
 REFERENCES DRIVERS (driverId);

  ALTER TABLE RESULTS
 ADD CONSTRAINT FK_constructors02 FOREIGN KEY (constructorId) 
 REFERENCES CONSTRUCTORS (constructorId);

  ALTER TABLE RESULTS
 ADD CONSTRAINT FK_statusId03 FOREIGN KEY (statusId) 
 REFERENCES STATUS (statusId);


 ALTER TABLE QUALIFYING
 ADD CONSTRAINT FK_raceId04 FOREIGN KEY (raceId) 
 REFERENCES RACES (raceId);
 
 ALTER TABLE QUALIFYING
 ADD CONSTRAINT FK_driverId05 FOREIGN KEY (driverId) 
 REFERENCES DRIVERS (driverId);
 
 ALTER TABLE QUALIFYING
 ADD CONSTRAINT FK_constructorId06 FOREIGN KEY (constructorId) 
 REFERENCES CONSTRUCTORS (constructorId);

 ALTER TABLE CONSTRUCTOR_RESULTS
 ADD CONSTRAINT FK_raceId07 FOREIGN KEY (raceId) 
 REFERENCES RACES (raceId);
 
 ALTER TABLE CONSTRUCTOR_RESULTS
 ADD CONSTRAINT FK_constructors08 FOREIGN KEY (constructorId) 
 REFERENCES CONSTRUCTORS (constructorId);

 ALTER TABLE DRIVER_STANDINGS
 ADD CONSTRAINT FK_raceId09 FOREIGN KEY (raceId) 
 REFERENCES RACES (raceId);
 
 ALTER TABLE DRIVER_STANDINGS
 ADD CONSTRAINT FK_driverId10 FOREIGN KEY (driverId) 
 REFERENCES DRIVERS (driverId);

 ALTER TABLE RACES
 ADD CONSTRAINT FK_circuitId11 FOREIGN KEY (circuitId) 
 REFERENCES CIRCUITS (circuitId);


ALTER TABLE PIT_STOPS
 ADD CONSTRAINT FK_raceId1 FOREIGN KEY (raceId)
 REFERENCES RACES (raceId);
 
 ALTER TABLE PIT_STOPS
 ADD CONSTRAINT FK_driverId12 FOREIGN KEY (driverId)
 REFERENCES DRIVERS (driverId);

ALTER TABLE SPRINT_RESULTS
 ADD CONSTRAINT FK_resultId13 FOREIGN KEY (resultId) 
 REFERENCES RESULTS (resultId);
 
 ALTER TABLE SPRINT_RESULTS
 ADD CONSTRAINT FK_raceId14 FOREIGN KEY (raceId)
 REFERENCES RACES (raceId);
 
 ALTER TABLE SPRINT_RESULTS
 ADD CONSTRAINT FK_driverId15 FOREIGN KEY (driverId)
 REFERENCES DRIVERS (driverId);
 
 ALTER TABLE SPRINT_RESULTS
 ADD CONSTRAINT FK_constructorId16 FOREIGN KEY (constructorId) 
 REFERENCES CONSTRUCTORS (constructorId);

 ALTER TABLE LAP_TIMES
 ADD CONSTRAINT FK_raceId17 FOREIGN KEY (raceId)
 REFERENCES RACES (raceId);
 
 ALTER TABLE LAP_TIMES
 ADD CONSTRAINT FK_driverId18 FOREIGN KEY (driverId)
 REFERENCES DRIVERS (driverId);


